"""salt_del

Revision ID: 0e00dd6f1002
Revises: eda01c95d8d2
Create Date: 2022-11-26 02:18:15.224591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e00dd6f1002"
down_revision = "eda01c95d8d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "auth", ["id"])
    op.drop_column("auth", "email")
    op.drop_column("auth", "salt")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth", sa.Column("salt", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "auth", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "auth", type_="unique")
    # ### end Alembic commands ###
