"""initial

Revision ID: 2c206b6f5d0d
Revises: 
Create Date: 2022-11-21 02:27:24.189114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c206b6f5d0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("origin_url", sa.String(), nullable=False),
        sa.Column("suffix", sa.String(), nullable=False),
        sa.Column("create_ts", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_url_origin_url"), "url", ["origin_url"], unique=False)
    op.create_index(op.f("ix_url_suffix"), "url", ["suffix"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_suffix"), table_name="url")
    op.drop_index(op.f("ix_url_origin_url"), table_name="url")
    op.drop_table("url")
    # ### end Alembic commands ###
