"""log

Revision ID: ffedf4b689e5
Revises: 0e00dd6f1002
Create Date: 2022-12-10 15:38:31.734870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffedf4b689e5'
down_revision = '0e00dd6f1002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_log')
    # ### end Alembic commands ###
